name: Bug report
description: Report a reproducible bug
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      options:
        - label: I searched existing issues
          required: true
        - label: This is not a security vulnerability
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is broken?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide minimal reproducible steps.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        OS:
        Runtime/toolchain version:
        Repo/component:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or output
      render: shell
